language: ruby
cache: bundler
before_install:
  # https://docs.travis-ci.com/user/languages/ruby/
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
  # - gem update --system # use the very latest Rubygems
  # - gem install bundler # use the very latest Bundler
dist: trusty
before_script:
  - unset _JAVA_OPTIONS
rvm:
  - 3.0
  - 2.7
  - 2.6
  - 2.5
  - 2.4
  - 2.3
  - 2.2
  - 2.1
  - jruby-9.2.17.0
  - ruby-head

gemfile:
  - gemfiles/rails_42.gemfile
  - gemfiles/rails_50.gemfile
  - gemfiles/rails_51.gemfile
  - gemfiles/rails_52.gemfile
  - gemfiles/rails_60.gemfile
  - gemfiles/rails_61.gemfile
  - gemfiles/rails_master.gemfile

env:
  global:
    - JRUBY_OPTS="-J-Xmx1024m --dev --debug"

matrix:
  fast_finish: true

  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.2.17.0
    - rvm: 2.1
      gemfile: gemfiles/rails_50.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_51.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_52.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_60.gemfile
    - rvm: 2.3
      gemfile: gemfiles/rails_60.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails_60.gemfile
    - rvm: 2.2
      gemfile: gemfiles/rails_60.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_61.gemfile
    - rvm: 2.3
      gemfile: gemfiles/rails_61.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails_61.gemfile
    - rvm: 2.2
      gemfile: gemfiles/rails_61.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_master.gemfile
    - rvm: 2.3
      gemfile: gemfiles/rails_master.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails_master.gemfile
    - rvm: 2.2
      gemfile: gemfiles/rails_master.gemfile
branches:
  only:
    - master
