language: ruby
cache: bundler
before_install:
  # https://docs.travis-ci.com/user/languages/ruby/
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
  # - gem update --system # use the very latest Rubygems
  # - gem install bundler # use the very latest Bundler
dist: trusty
before_script:
  - unset _JAVA_OPTIONS
rvm:
  - "3.0.0-preview1"
  - "2.7.2"
  - "2.6.6"
  - "2.5.5"
  - "2.4.6"
  - "2.3.8"
  - "2.2.10"
  - "2.1.10"
  - jruby-9.2.13.0

gemfile:
  - gemfiles/rails_42.gemfile
  - gemfiles/rails_50.gemfile
  - gemfiles/rails_51.gemfile
  - gemfiles/rails_52.gemfile
  - gemfiles/rails_60.gemfile

env:
  global:
    - JRUBY_OPTS="-J-Xmx1024m --dev --debug"
    - COVERAGE=true

matrix:
  fast_finish: true

  allow_failures:
    - rvm: jruby-9.1.16.0
      gemfile: gemfiles/rails_52.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_50.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_51.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_52.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_60.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/rails_60.gemfile
    - rvm: 2.4.6
      gemfile: gemfiles/rails_60.gemfile
    - rvm: 2.2.10
      gemfile: gemfiles/rails_60.gemfile
branches:
  only:
    - master
addons:
  code_climate:
    repo_token: 9c2feef5a1d636d5b08d10561c53f9293783fc175c0cc44d152cdb05a65d1868
